sonar.projectKey=JAL0NS0_juice-shop
sonar.projectName=Juice Shop - OWASP Security Training
sonar.projectVersion=19.1.1
sonar.organization=j-al0ns0

sonar.sources=app.ts,server.ts,lib,models,routes,data,views
sonar.sourceEncoding=UTF-8

sonar.exclusions=\
  **/node_modules/**,\
  **/build/**,\
  **/dist/**,\
  **/*.spec.ts,\
  **/*.test.ts,\
  cypress/**,\
  test/**,\
  frontend/node_modules/**,\
  monitoring/**,\
  vagrant/**,\
  encryptionkeys/**

sonar.javascript.lcov.reportPaths=\
  build/reports/coverage/server-tests/lcov.info,\
  build/reports/coverage/api-tests/lcov.info

sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx,.cts,.mts

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
sonar.newCodeDefinition=previous_version

sonar.host.url=https://sonarcloud.io
sonar.scm.disabled=false
sonar.scm.forceDetection=true
